apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexia-ai-core
  namespace: nextstep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexia-ai-core
  template:
    metadata:
      labels:
        app: nexia-ai-core
    spec:
      nodeSelector:
        node-pool: applications
      tolerations:
      - key: "node-pool"
        operator: "Equal"
        value: "applications"
        effect: "NoSchedule"
      containers:
      - name: ai-core
        image: nexia/ai-core:latest
        ports:
        - containerPort: 6000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nexia-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: nexia-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: nexia-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nexia-secrets
              key: anthropic-api-key
        envFrom:
        - configMapRef:
            name: nexia-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: nexia-ai-core-service
  namespace: nextstep
spec:
  selector:
    app: nexia-ai-core
  ports:
  - port: 6000
    targetPort: 6000
  type: ClusterIP
