apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic-fastcash
  namespace: unified-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic-fastcash
  template:
    metadata:
      labels:
        app: mautic-fastcash
    spec:
      initContainers:
      - name: postgres-init
        image: mautic/mautic:5.2.3-apache
        command: ["/bin/bash", "/init-postgres.sh"]
        volumeMounts:
        - name: postgres-init
          mountPath: /init-postgres.sh
          subPath: init-postgres.sh
      containers:
      - name: mautic
        image: mautic/mautic:5.2.3-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: postgres-init
          mountPath: /init-postgres.sh
          subPath: init-postgres.sh
        env:
        # Database Configuration
        - name: MAUTIC_DB_HOST
          value: "postgres-central.platform.svc.cluster.local"
        - name: MAUTIC_DB_PORT
          value: "5432"
        - name: MAUTIC_DB_NAME
          value: "fastcash_mautic"
        - name: MAUTIC_DB_USER
          value: "mautic_unified"
        - name: MAUTIC_DB_PASSWORD
          value: "mautic-postgres-2025"
        - name: MAUTIC_DB_DRIVER
          value: "pdo_pgsql"
        - name: MAUTIC_DB_SERVER_VERSION
          value: "14.18"
        - name: MAUTIC_SECRET_KEY
          value: "fastcash_secret_postgresql_2025"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: postgres-init
        configMap:
          name: mautic-postgres-init
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: mautic-fastcash
  namespace: unified-tools
spec:
  selector:
    app: mautic-fastcash
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP