apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexia-voice-whisper
  namespace: nexia-voice
  labels:
    app: nexia-voice-whisper
    component: speech-to-text
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexia-voice-whisper
  template:
    metadata:
      labels:
        app: nexia-voice-whisper
    spec:
      containers:
      - name: whisper-service
        image: registry.digitalocean.com/blueocean/nexia-whisper:latest
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_NAME
          value: "openai/whisper-large-v3"
        - name: DEVICE
          value: "cuda"
        - name: BATCH_SIZE
          value: "4"
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: model-cache
          mountPath: /app/models
        - name: audio-temp
          mountPath: /tmp/audio
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: nexia-models-pvc
      - name: audio-temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexia-voice-whisper-service
  namespace: nexia-voice
spec:
  selector:
    app: nexia-voice-whisper
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexia-voice-whisper-hpa
  namespace: nexia-voice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexia-voice-whisper
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80