apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    app: postgres-exporter
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_target]
      targetLabel: postgres_instance
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-alerts
  namespace: monitoring
  labels:
    app: postgres-monitoring
spec:
  groups:
  - name: postgres.rules
    interval: 30s
    rules:
    - alert: PostgreSQLDown
      expr: pg_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "PostgreSQL instance {{ $labels.postgres_instance }} is down"
        description: "PostgreSQL instance {{ $labels.postgres_instance }} has been down for more than 1 minute."

    - alert: PostgreSQLTooManyConnections
      expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL instance {{ $labels.postgres_instance }} has too many connections"
        description: "PostgreSQL instance {{ $labels.postgres_instance }} is using {{ $value | humanizePercentage }} of max connections."

    - alert: PostgreSQLHighDiskUsage
      expr: (pg_database_size_bytes / (1024^3)) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL database {{ $labels.datname }} disk usage is high"
        description: "Database {{ $labels.datname }} on {{ $labels.postgres_instance }} is using {{ $value }} GB of disk space."

    - alert: PostgreSQLReplicationLag
      expr: pg_replication_lag > 60
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL replication lag is high"
        description: "PostgreSQL replication lag on {{ $labels.postgres_instance }} is {{ $value }} seconds."

    - alert: PostgreSQLDeadTuples
      expr: pg_stat_user_tables_n_dead_tup > 1000
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL table {{ $labels.tablename }} has many dead tuples"
        description: "Table {{ $labels.schemaname }}.{{ $labels.tablename }} on {{ $labels.postgres_instance }} has {{ $value }} dead tuples."

    - alert: PostgreSQLSlowQueries
      expr: pg_stat_activity_max_tx_duration > 300
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL has slow running queries"
        description: "PostgreSQL instance {{ $labels.postgres_instance }} has queries running for more than 5 minutes."

    - alert: PostgreSQLHighCacheHitRatio
      expr: (pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read)) < 0.95
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL cache hit ratio is low"
        description: "PostgreSQL cache hit ratio on {{ $labels.postgres_instance }} is {{ $value | humanizePercentage }}."