apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexia-backend
  namespace: nexia
  labels:
    app: nexia-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexia-backend
  template:
    metadata:
      labels:
        app: nexia-backend
    spec:
      containers:
      - name: nexia-backend
        image: registry.digitalocean.com/onlyoneapi/nexia-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://nexia:password@postgres-central.platform.svc.cluster.local:5432/nexia"
        - name: REDIS_URL
          value: "redis://platform-pool-redis-master.platform.svc.cluster.local:6379/0"
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nexia-backend
  namespace: nexia
spec:
  selector:
    app: nexia-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
