apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-api-credentials
  namespace: platform
  labels:
    app: token-rotator
    component: security-automation
type: Opaque
stringData:
  # À remplir avec le token DigitalOcean API
  token: "REPLACE_WITH_DO_API_TOKEN"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-credentials
  namespace: platform
  labels:
    app: token-rotator
    component: security-automation
type: Opaque
stringData:
  # Optionnel : Webhook Slack pour notifications
  slack-webhook: "REPLACE_WITH_SLACK_WEBHOOK_URL"