apiVersion: v1
kind: Pod
metadata:
  name: kaniko-api-build
  namespace: nexia
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=dir:///workspace"
    - "--dockerfile=/workspace/Dockerfile"
    - "--destination=nexia-api:latest"
    - "--no-push"
    - "--tarPath=/workspace/nexia-api.tar"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  initContainers:
  - name: git-clone
    image: alpine/git:latest
    command:
    - /bin/sh
    - -c
    - |
      git clone https://github.com/ludovicpilet/kreach.git /tmp/repo
      cp -r /tmp/repo/nexia/api/* /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}