apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-nexia-supervisor-dev
  namespace: nexia-dev
  labels:
    app: nexia-supervisor
    build: kaniko
    env: dev
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
      - name: git-clone
        image: alpine/git:2.40.1
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Cloning NEXIA repository..."
          git clone https://oauth2:$(cat /etc/github/token)@github.com/Digiclevr/nexia.git /workspace/nexia
          cd /workspace/nexia
          echo "Repository cloned successfully"
          ls -la /workspace/nexia/apps/nexia-supervisor/
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: github-token
          mountPath: /etc/github
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v1.19.0-debug
        command: ["/kaniko/executor"]
        args: 
        - "--dockerfile=/workspace/nexia/apps/nexia-supervisor/Dockerfile"
        - "--context=/workspace/nexia/apps/nexia-supervisor"
        - "--destination=registry.digitalocean.com/blueocean/nexia-supervisor:dev-latest"
        - "--destination=registry.digitalocean.com/blueocean/nexia-supervisor:dev-$(date +%Y%m%d-%H%M%S)"
        - "--cache=true"
        - "--cache-repo=registry.digitalocean.com/blueocean/nexia-supervisor-cache"
        - "--compressed-caching=false"
        - "--snapshot-mode=redo"
        - "--use-new-run"
        - "--verbosity=info"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker
        env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
          allowPrivilegeEscalation: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: workspace
        emptyDir:
          sizeLimit: 2Gi
      - name: docker-config
        secret:
          secretName: registry-blueocean
          items:
          - key: .dockerconfigjson
            path: config.json
      - name: github-token
        secret:
          secretName: github-token
          items:
          - key: token
            path: token