apiVersion: v1
kind: Secret
metadata:
  name: nexia-secrets
  namespace: nexia-prod
type: Opaque
stringData:
  DATABASE_PASSWORD: "secure-nexia-password-2025"
  REDIS_AUTH: ""
  JWT_SECRET: "nexia-jwt-secret-ultra-secure-2025"
  DIRECTUS_KEY: "nexia-directus-key-2025"
  DIRECTUS_SECRET: "nexia-directus-secret-2025"
  DIRECTUS_DB_PASSWORD: "nexia-directus-db-password-2025"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: nexia-secrets-dev
  namespace: nexia-dev
type: Opaque
stringData:
  DATABASE_PASSWORD: "dev-nexia-password"
  REDIS_AUTH: ""
  JWT_SECRET: "dev-jwt-secret"
  DIRECTUS_KEY: "dev-directus-key"
  DIRECTUS_SECRET: "dev-directus-secret"
  DIRECTUS_DB_PASSWORD: "dev-directus-password"